### ISSUE TITLE
Storing user data in database.

### ISSUE THREAD

**Issue by sarapapa-sp** [rajsagare14/Blood-Distribution-System#3]
Storing the Users data of registration in database.

**Comment by sarapapa-sp** [comment]
@rajsagare14  can you assign this issue to me with hacktoberfest label.

**Comment by rajsagare14** [comment]
Check if it has been assigned

**Comment by rajsagare14** [comment]
@sarapapa-sp

**Comment by sarapapa-sp** [comment]
@rajsagare14  database not found .
Can you export your xampp server database in the database folder

**Comment by rajsagare14** [comment]
How @sarapapa-sp

**Comment by rajsagare14** [comment]
I have added the file @sarapapa-sp
